include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - omit_local_variable_types
    - prefer_single_quotes
    - unawaited_futures
